#!/usr/bin/env python3
"""
Run a single Optuna hyperparameter search trial.

Called by the SLURM array job generated by optuna_search.py.
Connects to a shared Optuna study (SQLite or other RDB storage) and
runs exactly one trial, reporting the result back to the study database.

Usage:
    python scripts/run_optuna_trial.py \\
        --study_name hedge_hpo_v1 \\
        --storage sqlite:////shared/path/hedge_hpo_v1.db \\
        --base_keyword default \\
        --metric val_iou \\
        --num_epochs_override 30 \\
        --pruning
"""

import argparse
import sys
import traceback
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import optuna

from src.training.search_space import sample_hyperparameters
from src.training.trainer import Trainer
from src.training.trainer_config import TrainerConfig


def parse_args():
    parser = argparse.ArgumentParser(description="Run a single Optuna HPO trial")
    parser.add_argument("--study_name", required=True, help="Optuna study name")
    parser.add_argument(
        "--storage",
        required=True,
        help="Optuna storage URL (e.g. sqlite:////abs/path/study.db)",
    )
    parser.add_argument(
        "--base_keyword",
        required=True,
        help="Predefined config keyword to use as the base config",
    )
    parser.add_argument(
        "--metric",
        default="val_iou",
        help=(
            "Metric to optimize. 'val_iou' uses trainer.metrics.best_iou (no final "
            "eval pass needed). Other options require the final eval: iou_valid, "
            "f1_valid, precision_valid, recall_valid (default: val_iou)"
        ),
    )
    parser.add_argument(
        "--num_epochs_override",
        type=int,
        default=None,
        help="Override num_epochs in base config (reduce for faster trials)",
    )
    parser.add_argument("--data_path", type=str, default=None)
    parser.add_argument("--save_path", type=str, default=None)
    parser.add_argument(
        "--metadata_dir",
        type=str,
        default=None,
        help="Directory containing train/valid/test metadata CSV files",
    )
    parser.add_argument("--batch_size", type=int, default=None, help="Batch size override")
    parser.add_argument("--num_workers", type=int, default=None, help="Dataloader workers override")
    parser.add_argument(
        "--pruning",
        action="store_true",
        help="Enable Optuna MedianPruner (reports val IoU each epoch)",
    )
    return parser.parse_args()


def load_metadata_from_dir(metadata_dir: str) -> dict:
    import geopandas as gpd
    import os

    metadata_frames = {}
    for file in os.listdir(metadata_dir):
        split_name = file.split(".")[0]
        metadata_frames[split_name] = gpd.read_file(os.path.join(metadata_dir, file))
    return metadata_frames


def build_objective(args):
    need_final_eval = args.metric != "val_iou"

    def objective(trial: optuna.Trial) -> float:
        override = sample_hyperparameters(trial)

        # Apply path overrides
        if args.data_path:
            override["data_path"] = args.data_path
        if args.save_path:
            override["save_path"] = args.save_path
        if args.batch_size is not None:
            override["batch_size"] = args.batch_size
        if args.num_workers is not None:
            override["num_workers"] = args.num_workers
        if args.num_epochs_override:
            override["num_epochs"] = args.num_epochs_override

        # Unique directory per trial so concurrent trials don't collide
        override["keyword"] = f"optuna_{args.study_name}_trial_{trial.number}"
        # Trials don't need permanent artifacts on disk
        override["save_results"] = False
        override["overwrite"] = True

        if args.metadata_dir:
            override["metadata_frames"] = load_metadata_from_dir(args.metadata_dir)

        config = TrainerConfig.get_predefined_config(
            keyword=args.base_keyword,
            override=override,
        )

        trainer = Trainer(config)
        trainer.setup()

        if args.pruning:
            def epoch_callback(epoch: int, val_iou: float):
                trial.report(val_iou, epoch)
                if trial.should_prune():
                    raise optuna.TrialPruned()

            trainer.epoch_callback = epoch_callback

        model, best_model_eval = trainer.train(
            save_results=False,
            skip_untrained_eval=True,
            skip_per_patch_eval=True,
        )

        if not need_final_eval:
            return trainer.metrics.best_iou

        value = best_model_eval.get(args.metric)
        if value is None:
            raise ValueError(
                f"Metric '{args.metric}' not found in eval dict. "
                f"Available keys: {list(best_model_eval.keys())}"
            )
        # evaluate_model_classification wraps values in single-element lists
        return value[0] if isinstance(value, list) else float(value)

    return objective


def main():
    args = parse_args()

    pruner = (
        optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=10)
        if args.pruning
        else optuna.pruners.NopPruner()
    )

    study = optuna.load_study(
        study_name=args.study_name,
        storage=args.storage,
        pruner=pruner,
    )

    print(f"Study '{args.study_name}' loaded. Running trial...")
    print(f"  Base config: {args.base_keyword}")
    print(f"  Metric: {args.metric}")
    print(f"  Epochs override: {args.num_epochs_override or 'none'}")
    print(f"  Pruning: {args.pruning}")

    try:
        study.optimize(build_objective(args), n_trials=1)
    except Exception as e:
        print(f"Trial failed with exception: {e}")
        traceback.print_exc()
        sys.exit(1)

    completed = [
        t for t in study.trials if t.state == optuna.trial.TrialState.COMPLETE
    ]
    if completed:
        best = study.best_trial
        print(
            f"\nStudy best so far: trial #{best.number}, {args.metric}={best.value:.4f}"
        )


if __name__ == "__main__":
    main()
